version: 0.2

#env:
phases:
  pre_build:
    commands:
      - yarn config set script-shell /bin/bash
      - yarn config set cache-folder /root/.yarn-cache
      - yarn #install --frozen-lockfile
      - ls -a
      - npx playwright install
  build:
    on-failure: ABORT
    commands:
      - yarn e2e
  post_build:
    commands:
      - npx nyc report --reporter=html
artifacts:
  files:
    - '**/*'
  base-directory: 'coverage'
