version: 0.2

phases:
  pre_build:
    commands:
      - yarn config set script-shell /bin/bash
      - yarn config set cache-folder /root/.yarn-cache
      - yarn #install --frozen-lockfile
  build:
    on-failure: ABORT
    commands:
      - yarn build-e2e
  # post_build:
  #   commands:
  #     - aws cloudfront create-invalidation --distribution-id=$DISTROBUTIONID --paths '/*'
artifacts:
  enable-symlinks: true
  secondary-artifacts:
    TestFilesArtifact:
      files:
        - '**/*'
      name: TestFilesArtifact
    TestBuildArtifact:
      files:
        - '**/*'
      name: TestBuildArtifact
      base-directory: build
    enable-symlinks: true
