version: 0.2

phases:
  pre_build:
    commands:
      - yarn config set script-shell /bin/bash
      - yarn config set cache-folder /root/.yarn-cache
      - yarn #install --frozen-lockfile
  build:
    on-failure: ABORT
    commands:
      - yarn build-e2e
  # post_build:
  #   commands:
  #     - aws cloudfront create-invalidation --distribution-id=$DISTROBUTIONID --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: build
  secondary-artifacts:
    TestFiles:
      files:
        - '**/*'
      name: TestFilesArtifact
      base-directory: e2e
